esphome:
  name: bedroom_ceiling_light
  comment: Bedroom Ceiling Light

esp8266:
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  ap:
    ssid: Bedroom Ceiling Light
    password: !secret wifi_ap_password
    ap_timeout: 5min

captive_portal:

logger:

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: !secret time_timezone

output:
  - platform: gpio
    pin: 14
    id: relay_1
    inverted: false

light:
  - platform: binary
    name: Bedroom Ceiling Light
    output: relay_1
    id: light_1

binary_sensor:
  - platform: gpio
    pin:
      number: 5
      mode: INPUT_PULLUP
    on_state:
      then:
        - light.toggle: light_1
    internal: true
    id: switch_1

  - platform: status
    name: Bedroom Ceiling Light Status

sensor:
  - platform: wifi_signal
    name: Bedroom Ceiling Light Signal
