esphome:
  name: bedroom_bed
  comment: Bedroom Bed
  platform: ESP32
  board: pico32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none

  ap:
    ssid: Bedroom Bed
    password: !secret wifi_ap_password
    ap_timeout: 5min

captive_portal:

logger:

api:
  reboot_timeout: 0s

ota:

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: !secret time_timezone

esp32_touch:
  setup_mode: false
  # See https://github.com/esphome/issues/issues/1151
  # iir_filter: 10ms
  high_voltage_reference: 2.7V
  low_voltage_reference: 0.5V
  voltage_attenuation: 0.5V

binary_sensor:
  - platform: esp32_touch
    id: left
    pin: GPIO15
    threshold: 9
    filters:
      - delayed_on_off: 2s

  - platform: esp32_touch
    id: right
    pin: GPIO2
    threshold: 9
    filters:
      - delayed_on_off: 2s

  - platform: template
    name: Bedroom Bed Occupancy
    device_class: occupancy
    lambda: |-
      if (id(left).state || id(right).state) {
        return true;
      } else {
        return false;
      }

  - platform: status
    name: Bedroom Bed Status

sensor:
  - platform: wifi_signal
    name: Bedroom Bed Signal
