esphome:
  name: kitchen_ceiling_light
  comment: Kitchen Ceiling Light

esp8266:
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  ap:
    ssid: Kitchen Ceiling Light
    password: !secret wifi_ap_password
    ap_timeout: 5min

captive_portal:

logger:

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: !secret time_timezone

switch:
  - platform: gpio
    name: Kitchen Ceiling Light Switch
    pin:
      number: 14
      inverted: false
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: gpio
    name: Kitchen Ceiling Light Button
    pin:
      number: 5
      mode: INPUT_PULLUP

  - platform: status
    name: Kitchen Ceiling Light Status

sensor:
  - platform: wifi_signal
    name: Kitchen Ceiling Light Signal
