esphome:
  name: kitchen_ceiling_light
  comment: Kitchen Ceiling Light
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  ap:
    ssid: "Kitchen Ceiling Light"
    password: !secret wifi_ap_password
    ap_timeout: 5min

captive_portal:

logger:

api:

ota:

output:
  - platform: gpio
    pin: 14
    id: relay_1
    inverted: False

light:
  - platform: binary
    name: "Kitchen Ceiling Light"
    output: relay_1
    id: light_1

binary_sensor:
  - platform: gpio
    pin:
      number: 5
      mode: INPUT_PULLUP
    on_state:
      then:
        - light.toggle: light_1
    internal: true
    id: switch_1
  - platform: status
    name: "Kitchen Ceiling Light Status"

sensor:
  - platform: wifi_signal
    name: "Kitchen Ceiling Light Signal"
    update_interval: 60s
