esphome:
  name: lelit_marax
  comment: Lelit MaraX

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  min_auth_mode: WPA2

  ap:
    ssid: Lelit MaraX
    password: !secret wifi_ap_password
    ap_timeout: 5min

captive_portal:

logger:

api:
  reboot_timeout: 15min

ota:
  - platform: esphome

uart:
  # tx_pin: D6
  rx_pin:
    number: D5
    inverted: true
  baud_rate: 9600
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      delimiter: "\n"
    sequence:
      - lambda: |-
          UARTDebug::log_string(direction, bytes);

          char priority[1];
          char firmware[4];
          int steamActual=0;
          int steamTarget=0;
          int hxActual=0;
          int boost=0;
          int heating=0;

          std::string str(bytes.begin(), bytes.end());

          if (sscanf(str.c_str(), "%1c%4c,%d,%d,%d,%d,%d", priority, firmware, &steamActual, &steamTarget, &hxActual, &boost, &heating) == 7 ) {
            id(is_heating).publish_state(heating);
            id(hx_temperature).publish_state(hxActual);
            id(steam_temperature).publish_state(steamActual);
            id(reset).execute();
          }

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: !secret time_timezone

binary_sensor:
  - platform: status
    name: Lelit MaraX Status

  - platform: template
    id: is_heating
    name: "Lelit MaraX Heating"
    device_class: running
    icon: mdi:heating-coil

  - platform: template
    id: is_hx_ready
    name: "Lelit MaraX HX Ready"
    icon: mdi:coffee-maker
    condition:
      sensor.in_range:
        id: hx_temperature
        above: 93.5
        below: 94.5

  - platform: template
    id: is_steam_ready
    name: "Lelit MaraX Steam Ready"
    icon: mdi:kettle-steam
    condition:
      sensor.in_range:
        id: steam_temperature
        above: 123.5

sensor:
  - platform: wifi_signal
    name: Lelit MaraX Signal

  - platform: template
    id: hx_temperature
    name: "Lelit MaraX HX Temperature"
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    icon: mdi:thermometer
    filters:
      - throttle_average: 10s

  - platform: template
    id: steam_temperature
    name: "Lelit MaraX Steam Temperature"
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    icon: mdi:thermometer
    filters:
      - throttle_average: 10s

script:
  - id: reset
    mode: restart
    then:
      - delay: 10s
      - lambda: |-
          id(is_heating).publish_state(0);
          id(hx_temperature).publish_state(NAN);
          id(steam_temperature).publish_state(NAN);
