esphome:
  name: living_room_ceiling_light
  comment: Living Room Ceiling Light

esp8266:
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  min_auth_mode: WPA2

  ap:
    ssid: Living Room Ceiling Light
    password: !secret wifi_ap_password
    ap_timeout: 5min

captive_portal:

logger:

api:
  reboot_timeout: 15min

ota:
  - platform: esphome

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: !secret time_timezone

switch:
  - platform: gpio
    name: Living Room Light Switch
    pin:
      number: 14
      inverted: false
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: gpio
    name: Living Room Ceiling Light Button
    pin:
      number: 5
      mode: INPUT_PULLUP

  - platform: status
    name: Living Room Ceiling Light Status

sensor:
  - platform: wifi_signal
    name: Living Room Ceiling Light Signal
